blog/blog/urls.py
from django.contrib import admin, staticfiles
from django.urls import path,include
from django.views.generic import RedirectView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('context/', include('context.urls')),
    path('', RedirectView.as_view(url='/context/')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('tinymce/',include('tinymce.urls')),
    
]
urlpatterns += staticfiles_urlpatterns()

blog/context/urls.py
from django.urls import path
from . import views
from django.contrib import staticfiles
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'blog'

urlpatterns = [    
	path('', views.index, name='index'),
	path('aboutme', views.aboutme, name='aboutme'),
	path('list', views.list, name='list'),
	path('new', views.new, name='new'),
	path('<int:id>', views.detail, name='detail'),
	path('<int:id>/delete', views.delete, name='delete'),
	path('create', views.create, name='create'),
	path('<int:id>/edit', views.edit, name='edit'),
	path('<int:id>/update', views.update, name='update'),
]
urlpatterns += staticfiles_urlpatterns()

blog/context/models.py
from django.db import models
from datetime import datetime


class Blog_Posts(models.Model):
	
	title = models.CharField(max_length=200)
	content = models.TextField()
	published_time = models.DateTimeField("date published",default=datetime.now())
	
	def __str__(self):
		return self.title

blog/context/forms.py
from django import forms
from .models import *
from datetime import datetime

class BlogEditForm(forms.ModelForm):
	class Meta:
		model = Blog_Posts
		fields = (
			"title",
			"content")  

		

blog/context/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Blog_Posts
from .forms import *
# from django.contrib.auth.mixins import LoginRequiredMixin
# from django.views.generic import TemplateView 


def index(request):
	return render(request,'context/index.html')

def aboutme(request):
	return render(request,'context/aboutme.html')

def list(request):
	blog_post = Blog_Posts.objects.all()

	context ={
		"blog_post":blog_post,
	}
	return render(request,'context/list.html',context)

def detail(request, id):
	blog_post = get_object_or_404(Blog_Posts, pk=id)

	context ={
		"blog_post":blog_post,
	}
	return render(request,'context/detail.html',context)

def delete(request, id):
    blog_post = get_object_or_404(Blog_Posts, pk=id)
    blog_post.delete()

    blog_posts = Blog_Posts.objects.all()
    context = {
        'message': '削除',
        'blog_posts': blog_posts,
    }
    return render(request, 'context/delete.html', context)

def edit(request, id):
    blog_posts = get_object_or_404(Blog_Posts, pk=id)
    blogEditForm = BlogEditForm(instance=blog_posts)

    context = {
        
        'blog_posts': blog_posts,
        'blogEditForm': blogEditForm,
    }
    return render(request, 'context/edit.html', context)

def update(request, id):
    if request.method == 'POST':
        blog_post = get_object_or_404(Blog_Posts, pk=id)
        blogEditForm = BlogEditForm(request.POST, instance=blog_post)
        if blogEditForm.is_valid():
            blogEditForm.save()

    context = {
        'message': 'Update memo ' + str(id),
        'blog_post': blog_post,
    }
    return render(request, 'context/detail.html', context)

def create(request):
    if request.method == 'POST':
        blogEditForm = BlogEditForm(request.POST)
        if blogEditForm.is_valid():
            blog_post = blogEditForm.save()

    context = {
        'message': 'Create blog_post ',
        'blog_post': blog_post,
    }
    return render(request, 'context/detail.html', context)

def new(request):
    blogEditForm = BlogEditForm()

    context = {
        'message': 'New blog_post',
        'blogEditForm': blogEditForm,
    }
    return render(request, 'context/new.html', context)

blog/context/templates/context/aboutme.html
{% extends './base.html' %}
{% load staticfiles %}
{% block content %}

<div class="jumbotron">
	<div class="container">
		<div class="row">
			<div class="col-sm-6">
				<h1><strong>Izumi</strong>のページ</h1>
				<p class="lead">V-tuberプログラマーのポートフォリオ公開中。</p>
			</div>
			<div class="col-sm-6">
				<img src="/static/img/Izumi_photo2.png" height="480px" alt="izumisyasinn">
			</div>
		</div>
	</div>
</div>

<div class="container">
	<div class="starter-template">
		<div class="row text-center">
			<h2 style="font-family: 'Yusei Magic'; font-size: 260%;">見かけによらず、個性的でチャーミング！！</h2>
			<div class="col-sm-4">
				<h2 class="color-talk"><i class="bi bi-chat-left-text icon-size" ></i><br>しゃべる</h2>
				<p>コミュニケーション能力が高く、<br>中国語と日本語と英語<br>が話せる。</p>
			</div>
			<div class="col-sm-4">
				<h2 class="color-wrench"><span class="bi bi-wrench icon-size"></span><br>つくる</h2>
				<p>学生時代に自分でC#でPost　SystemとLineのChatBotを作た、<br>就業までにpythonで写真の分類をした、<br>今様々開発経験を積んでいる。</p>
			</div>
			<div class="col-sm-4">
				<h2 class="color-heart"><span class="bi bi-hand-thumbs-up-fill icon-size"></span><br>たよる</h2>
				<p>チームに仕事を割り当てで、<br>指揮ことを担当する。<br>相談と安心のキャラです。</p>
			</div>
		</div>
		<hr>
		<h2 style="font-size:35px;">Side Projects</h2>
		<div class="row">
			<div class="col-sm-6">
				<h3>Order System</h3>
				<p>初プロジェト、操作が易い使う、基本的な飲み物の注文システム。管理登録やメニュー編集やトータルレポートの機能があります。</p>
				<img src="/static/img/system.jpg" style="float:right;width:500px;height:500px;" >
			</div>
			<div class="col-sm-6">
				<img src="/static/img/orders-login.PNG" style="float:left;width:500px;height:550px;"  >

			</div>
		</div>
		<p></p>
		<div class="row">
			<div class="col-sm-6">
				<h3>健康相談 - 健康向け相談Line bot</h3>
				<p>今の社会忙しくて、ストレスいっぱくて、色々文明病気出た。もし、病院へいかない時間はこの相談ボットは参考ができが、あとは必ず病院へ行って検査しなければいけません。このデータベースはいっぱい病院の病気の資料を収集したと整理した。食べ物のカロリーも検索ができる。Lineで知りたい情報が易い手に入る。</p>
			</div>
			<div class="col-sm-6">
				<img src="/static/img/health-v.jpg" style="float:left;width:500px;" alt="health-app-img" >
			</div>
		</div>
		<p></p>
		<div class="row">
			<div class="col-sm-6">
				<h3>害蟲区別</h3>
				<p>2019から台湾の畑にツマジロクサヨトウを発見した。ですが、色々虫とツマジロクサヨトウとても似ている、農夫は判断が難しい。その問題ために台湾に見られる虫とツマジロクサヨトウの写真を収集して、深層学習のモデルで分析した。</p>
			</div>
			<div class="col-sm-6">
				<img src="/static/img/python-bug-cnn.jpg"　 style="float:left;width:500px;" alt="python-bug-cnn-img" >
			</div>
		</div>
		<div class="row">
			<div class="col-sm-12">
				<h3>Others</h3>
				<ul>
					<li><a href="https://github.com/Kouichi1229"><i class="bi bi-github"></i>Kouichi1229</a></li>
					<li><a href="https://twitter.com/home"><i class="bi bi-twitter"></i>@VtuberIzumi</a></li>
					<li><a href="https://www.youtube.com/"><i class="bi bi-youtube"></i>izumiいずみ ch</a></li>
				</ul>
			</div>
		</div>
		<hr>
		<h2 id="skills">Skills</h2>
		<div class="row">
			<div class="col-sm-12">
				<h3>Programing Language</h3>
				<ul>
					<li>Python <b>作品:害蟲区別(TensorFlow API)、このBlog(Django)</b></li>
					<li>C＃ <b>作品:Order System、健康相談(Net.C# + Azure)</b></li>
					<li>JAVA</li>
				</ul>

				<h3>Database</h3>
				<ul>
					<li>Mysql</li>
				</ul>
			</div>
		</div>
		<a class="btn btn-outline-secondary" href="#" style="float: right;">Topに戻る</a>
		<p></p>
	</div>
</div>
{% endblock %}

blog/context/templates/context/base.html
<!DOCTYPE html>
<html>    
<head>        
  <meta charset='utf-8'>
  <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>        
  <title>Izumi Blog</title>
  <!-- css -->
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <!-- bootstrap  -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">
  <!--Chat.js-->
  <script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js'></script>
  <!--js-->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


  <!-- icon  -->
  <link rel="icon" href="/static/img/New Piskel-1.png.ico"  type="image/x-icon">   
  <!-- Text/Typography  -->
  <link href="https://fonts.googleapis.com/css2?family=Kosugi&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Kosugi&family=Kosugi+Maru&family=Shippori+Mincho+B1:wght@700&display=swap" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Potta+One&display=swap" rel="stylesheet">   
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Potta+One&family=Yusei+Magic&display=swap" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Potta+One&family=Stick&family=Yusei+Magic&display=swap" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@500&display=swap" rel="stylesh">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@500;700&display=swap" rel="stylesheet">
  <style>
    body {
      padding-top: 50px;
    }

    .icon-size {
      font-size: 200%;
    }

    h1 {
      font-family: 'Kosugi', sans-serif;
    }

    p{
      font-family: 'Kosugi Maru', sans-serif;
    }

    .starter-template {
      padding: 40px 80px;
      background-color: white;
    }

    .icon-size {
      font-size: 200%;
    }
    .color-talk {
      color: lightseagreen;
    }

    .color-wrench {
      color: steelblue;
    }

    .color-heart {
      color: plum;
    }

    .bar {
      margin-bottom: 10px;
      width: 0;
      padding: 5px 10px;
    }

    #Nav_font{
      font-family:'Potta One', cursive;
    }

    #logo {
      overflow: hidden;
      height: 250px;
    }

    #page {
      overflow: hidden;
      padding: 20px 20px 40px 20px;
    }



  </style>   
</head>    
<body>        
 <nav class="navbar navbar-expand-md bg-dark navbar-dark">
   <a class="navbar-brand" href="{% url 'blog:index' %}">
    <img src="/static/img/New Piskel-1.png.ico" alt="logo" style="width:40px;">
  </a>
  <a class="navbar-brand" href="{% url 'blog:index' %}" id="Nav_font">Izumiの家</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class='navbar-brand' href="{% url 'blog:list'%}" id="Nav_font">IT勉強帳</a>
      </li>
      <li class="nav-item">
        <a class='navbar-brand' href="{% url 'blog:aboutme' %}" id="Nav_font" >About Me</a>
      </li>
      {% if user.is_authenticated %}
      <li class='nav-time'>
        <span class='navbar-text'>{{ user }} - </span>
      </li>
      <li class='nav-item'>
        <a href='{% url "logout" %}' class='logout nav-link'>Logout</a>
      </li>
      {% else %}
      <a href='{% url "login" %}' class='login nav-link'>Login</a>
      {% endif %}    
    </ul>
  </div>  
</nav>
<br>
<div class='container'>            
  {% block content %}            
  {% endblock %}        
</div>
<!-- footer -->   
<div>
  <div class="jumbotron" >
    <div class="row">
      <div class="col-sm-6">
        <p><a href="{% url 'blog:index' %}">Izumiの家</a> | 
          <a href="{% url 'blog:list'%}">IT勉強帳</a> | 
          <a href="{% url 'blog:aboutme' %}">About Me</a></p>
        <p></p>
        <p>Copyright © 2021 Izumi. All rights reserved.</p>
        <p>版權所有© 2021 Izumi</p>
      </div>
      <div class="col-sm-6">
        <a href="https://github.com/Kouichi1229"><i class="bi bi-github"></i></a>
        <a href="https://twitter.com/home"><i class="bi bi-twitter"></i></a>
        <a href="https://www.youtube.com/"><i class="bi bi-youtube"></i></a>
      </div>
    </div>
  </div>
</div> 
<!-- jQuery and JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-LCPyFKQyML7mqtS+4XytolfqyqSlcbB3bvDuH9vX2sdQMxRonb/M3b9EmhCNNNrV" crossorigin="anonymous"></script>
</body>
</html>

blog/context/templates/context/delete.html
{% extends './base.html' %}
{% load staticfiles %}
{% block content %}
<br>
<h1>{{message}}</h1>
<h2>{{ blog_posts.title }}</h2>
<a href="{% url 'blog:list'  %}" class='btn btn-outline-primary'>戻る/Back</a>
{% endblock %}

blog/context/templates/context/detail.html
{% extends 'layout.html' %}
{% load staticfiles %}
{% load static %}
{% block content %}

<!-- Prism CSS -->
<link href="{% static 'tinymce/css/prism.css' %}" rel="stylesheet">


<div class="w3-main" style="margin-left:250px">

  <div class="w3-row w3-padding-64">
    <div class="w3-twothird w3-container">
      <h1 class="w3-text-teal">{{ blog_post.title }}</h1>
      <p>{{ blog_post.published_time }}</p>
      <p>{{ blog_post.content | safe }}</p>
    </div>
    <div class="w3-third w3-container">
      <a href="#"><p class="w3-border w3-padding-large w3-padding-32 w3-center"></p></a>
      <a href="#"><p class="w3-border w3-padding-large w3-padding-64 w3-center"></p></a>
    </div>
  </div>
  <br>
  <p><a href="{% url 'blog:list'  %}" class='btn btn-outline-primary'>戻る/Back</a>
    {% if user.is_authenticated %}
    <a href="{% url 'blog:delete' blog_post.id  %}" class='btn btn-outline-danger'>削除</a> 
    <a href="{% url 'blog:edit' blog_post.id  %}" class='btn btn-outline-success'>編集</a>  
    {% endif %}
    
  </p>
  {% endblock %}

blog/context/templates/context/edit.html
{% extends './base.html' %}
{% load bootstrap4 %}

{% block content %}
    <h1>{{ message }}</h1>

    <form action='{% url "blog:update" blog_posts.id %}' method='post' class='form'>
        {% csrf_token %}
        {% bootstrap_form blogEditForm layout='horizontal' %}
        <br>
        <button type='submit' class='btn btn-outline-primary'>保存する</button>
        <a href='{% url "blog:detail" blog_posts.id %}' class='btn btn-outline-secondary'>戻る</a>
    </form>
{% endblock %}

blog/context/templates/context/list.html
{% extends './base.html' %}
{% load staticfiles %}
{% block content %}

<header class="w3-container w3-center w3-padding-32"> 
	<h1><b>IT勉強帳</b></h1>
	<br>
	{% if user.is_authenticated %}
	<a href="{% url 'blog:new'  %}" class='btn btn-outline-danger'>New</a>  
	{% endif %}

</header>

<!-- 文章 -->
<!-- Grid -->
<div class="w3-row">
	{% for post in blog_post %}
	<!-- Blog entries -->
	<div class="w3-col l8 s12">
		<!-- Blog entry -->
		<div class="w3-card-4 w3-margin w3-white">
			<div class="w3-container">
				<h3><b>{{post.title}}</b></h3>
				<h5><span class="w3-opacity">{{ post.published_time }}</span></h5>
			</div>

			<div class="w3-container">
				<div class="w3-row">
					<div class="w3-col m8 s12">
						<p><a href="{% url 'blog:detail' post.id %}" class="w3-button w3-padding-large w3-white w3-border"><b>READ MORE »</b>
						</a></p>
					</div>
					<div class="w3-col m4 w3-hide-small">
					</div>
				</div>
			</div>
		</div>
		<hr>  
	</div>
	{% endfor %}


	<!-- Pagination -->
	<div class="w3-row">
		<div class="w3-center w3-padding-64">
			<div class="w3-bar">
				<a class="w3-button w3-black" href="#">1</a>
				<a class="w3-button w3-hover-black" href="#">2</a>
				<a class="w3-button w3-hover-black" href="#">3</a>
				<a class="w3-button w3-hover-black" href="#">4</a>
				<a class="w3-button w3-hover-black" href="#">5</a>
				<a class="w3-button w3-hover-black" href="#">»</a>
			</div>
		</div>
	</div>

	{% endblock %}

blog/context/templates/context/new.html
{% extends './base.html' %}
{% load bootstrap4 %}
{% block content %}

 <form action='{% url "blog:create" %}' method='post' class='form'>
	{% csrf_token %}
	{% bootstrap_form blogEditForm layout='horizontal' %}

	<br>
	<button type='submit' class='btn btn-outline-primary'>作成する</button>
	<a href='{% url "blog:list" %}' class='btn btn-outline-secondary'>戻る</a>

</form>
	
{% endblock %}

blog/templates/layout.html
<!DOCTYPE html>
<html>    
<head>        
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>        
    <title>Izumi Blog</title>
    <!-- css -->
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- bootstrap  -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">
    <!--Chat.js-->
    <script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js'></script>
    <!--js-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    

    <!-- icon  -->
    <link rel="icon" href="/static/img/New Piskel-1.png.ico"  type="image/x-icon">   
    <!-- Text/Typography  -->
    <link href="https://fonts.googleapis.com/css2?family=Kosugi&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Kosugi&family=Kosugi+Maru&family=Shippori+Mincho+B1:wght@700&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Potta+One&display=swap" rel="stylesheet">   
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Potta+One&family=Yusei+Magic&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Potta+One&family=Stick&family=Yusei+Magic&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@500&display=swap" rel="stylesh">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@500;700&display=swap" rel="stylesheet">

    <style>
        body {
            padding-top: 50px;
        }

        .icon-size {
            font-size: 200%;
        }

        h1 {
            font-family: 'Kosugi', sans-serif;
        }

        p{
            font-family: 'Kosugi Maru', sans-serif;
        }

        .starter-template {
            padding: 40px 80px;
            background-color: white;
        }

        .icon-size {
            font-size: 200%;
        }
        .color-talk {
            color: lightseagreen;
        }

        .color-wrench {
            color: steelblue;
        }

        .color-heart {
            color: plum;
        }

        .bar {
            margin-bottom: 10px;
            width: 0;
            padding: 5px 10px;
        }

        #Nav_font{
            font-family:'Potta One', cursive;
        }

        #logo {
            overflow: hidden;
            height: 250px;
        }

        #page {
            overflow: hidden;
            padding: 20px 20px 40px 20px;
        }

    </style>   
</head>    
<body>        
  <nav class='navbar navbar-expand-sm navbar-dark bg-dark fixed-top'>
    <a class="navbar-brand" href="{% url 'blog:index' %}">
        <img src="/static/img/New Piskel-1.png.ico" alt="logo" style="width:40px;">
    </a>
    <a class="navbar-brand" href="{% url 'blog:index' %}" id="Nav_font">Izumiの家</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class='navbar-brand' href="{% url 'blog:list'%}" id="Nav_font">IT勉強帳</a>
        </li>
        <li class="nav-item">
            <a class='navbar-brand' href="{% url 'blog:aboutme' %}" id="Nav_font" >About Me</a>
        </li>
        {% if user.is_authenticated %}
        <li class='nav-time'>
            <span class='navbar-text'>{{ user }} - </span>
        </li>
        <li class='nav-item'>
            <a href='{% url "logout" %}' class='logout nav-link'>Logout</a>
        </li>
        {% else %}
        <a href='{% url "login" %}' class='login nav-link'>Login</a>
        {% endif %}
    </ul>
</nav>
<div class='container'>
    {% block content %}
    {% endblock %} 
</div>
<!-- footer -->   
<div>
    <div class="jumbotron" >
        <p><a href="{% url 'blog:index' %}">Izumiの家</a> | <a href="{% url 'blog:list'%}">IT勉強帳</a> | <a href="{% url 'blog:aboutme' %}">About Me</a></p>
        <p></p>
        <p>Copyright © 2021 Izumi. All rights reserved.</p>
        <p>版權所有© 2021 Izumi</p>
    </div>
</div> 
<!-- jQuery and JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-LCPyFKQyML7mqtS+4XytolfqyqSlcbB3bvDuH9vX2sdQMxRonb/M3b9EmhCNNNrV" crossorigin="anonymous"></script>
</body>
</html>